theme       : jekyll-theme-slate
title       : "SuperSaiyajinStackZ"
description : "SuperSaiyajinStackZ's site"
repo        : "SuperSaiyajinStackZ/SuperSaiyajinStackZ.github.io"
color       : "#3280D9"
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html,cpp"

defaults:
  -
    values:
      layout: "default"
      title: "SuperSaiyajinStackZ"